# Generated by Django 6.0 on 2026-02-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('bilgisayar_prog', 'Bilgisayar Programcılığı'), ('elektrik', 'Elektrik'), ('insaat', 'İnşaat')], max_length=50, null=True, verbose_name='Bölüm'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_points',
            field=models.IntegerField(default=0, verbose_name='Toplam Öğrenci Puanı'),
        ),
    ]
