# Generated by Django 6.0 on 2026-02-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='total_points',
            field=models.PositiveIntegerField(default=0, verbose_name='Toplam Puan'),
        ),
    ]
