# Generated by Django 6.0 on 2026-02-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_total_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('ilahiyat', 'İlahiyat'), ('isg', 'İş Sağlığı Ve Güvenliği'), ('beslenmevediyetetik', 'Beslenme Ve Diyetetik'), ('hemsirelik', 'Hemşirelik'), ('saglikkurumlarıisletmeciligi', 'Sağlık Kurumları İşletmeciliği'), ('webtasarimvekodlama', 'Web Tasarım Ve Kodlama')], max_length=50, null=True, verbose_name='Bölüm'),
        ),
    ]
