# Generated by Django 6.0 on 2026-10-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0007_alter_user_department'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='emailotp',
            index=models.Index(fields=['email', 'code'], name='users_email_email_50710d_idx'),
        ),
        migrations.AddIndex(
            model_name='emailotp',
            index=models.Index(fields=['created_at'], name='users_email_created_06b128_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_staff', 'is_teacher', 'department'], name='users_user_is_staf_6e7dbf_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_student', 'department'], name='users_user_is_stud_29f0c6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['department', 'total_points'], name='users_user_departm_49c233_idx'),
        ),
    ]
