# Generated by Django 6.0 on 2026-10-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0008_emailotp_users_email_email_50710d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kategori'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['category'], name='users_user_categor_1173e8_idx'),
        ),
    ]
