# Generated by Django 6.0 on 2026-10-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_category_user_users_user_categor_1173e8_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('siyasetbilimivekamuyonetimi', 'Siyaset Bilimi Ve Kamu Yönetimi'), ('turkdiliveedebiyati', 'Türk Dili Ve Edebiyatı'), ('matematik', 'Matematik')], max_length=50, null=True, verbose_name='Bölüm'),
        ),
    ]
