# Generated by Django 6.0 on 2026-01-26 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='completedmaterial',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='introvideocompletion',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intro_status', to=settings.AUTH_USER_MODEL, verbose_name='Öğrenci'),
        ),
        migrations.AddField(
            model_name='completedmaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.material'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='material',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='contents.material'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='contents.quiz'),
        ),
        migrations.AddField(
            model_name='quizoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='contents.quizquestion'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.quizquestion'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='selected_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.quizoption'),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentquestion',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentquizattempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.quiz'),
        ),
        migrations.AddField(
            model_name='studentquizattempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='contents.studentquizattempt'),
        ),
        migrations.AddField(
            model_name='timetracking',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timetracking',
            name='weekly_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.weeklycontent'),
        ),
        migrations.AddField(
            model_name='studentquestion',
            name='weekly_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.weeklycontent'),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='weekly_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.weeklycontent'),
        ),
        migrations.AddField(
            model_name='material',
            name='parent_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='contents.weeklycontent'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='weekly_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='contents.weeklycontent'),
        ),
        migrations.AlterUniqueTogether(
            name='completedmaterial',
            unique_together={('student', 'material')},
        ),
        migrations.AlterUniqueTogether(
            name='studentprogress',
            unique_together={('student', 'weekly_content')},
        ),
    ]
