# Generated by Django 6.0 on 2026-02-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='point_value',
            field=models.PositiveIntegerField(default=0, verbose_name='Tamamlama Puanı'),
        ),
        migrations.AlterField(
            model_name='material',
            name='content_type',
            field=models.CharField(choices=[('video', 'Video'), ('podcast', 'Podcast'), ('form', 'Bilgi Testi'), ('pdf', 'Ders Notu (PDF)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='material',
            name='embed_url',
            field=models.URLField(help_text='Video/Podcast embed kodu veya OneDrive PDF indirme linki.', verbose_name='Materyal Linki'),
        ),
    ]
