# Generated by Django 6.0 on 2026-02-05 03:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_material_point_value_alter_material_content_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='completedmaterial',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='completedmaterial',
            name='repetition_cycle',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='studentquizattempt',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='completedmaterial',
            name='completed_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='completedmaterial',
            unique_together={('student', 'material', 'repetition_cycle')},
        ),
    ]
