# Generated by Django 6.0 on 2026-02-05 07:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_alter_completedmaterial_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='completedmaterial',
            unique_together={('student', 'material')},
        ),
        migrations.RemoveField(
            model_name='studentquizattempt',
            name='attempt_number',
        ),
        migrations.AlterField(
            model_name='completedmaterial',
            name='completed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.RemoveField(
            model_name='completedmaterial',
            name='repetition_cycle',
        ),
    ]
