# Generated by Django 6.0 on 2026-02-05 20:20

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_alter_completedmaterial_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flashcard',
            options={'ordering': ['order'], 'verbose_name': 'Flashcard Aktivitesi', 'verbose_name_plural': 'Flashcard Aktiviteleri'},
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='question',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='activity_url',
            field=models.URLField(default=datetime.datetime(2026, 2, 5, 20, 20, 14, 234235, tzinfo=datetime.timezone.utc), help_text='Microsoft Learning Activities veya iframe destekli flashcard linkini buraya yapıştırın.', verbose_name='Aktivite Linki'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flashcard',
            name='title',
            field=models.CharField(default='Haftalık Tekrar Aktivitesi', max_length=255, verbose_name='Aktivite Başlığı'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Sıralama'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='weekly_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='contents.weeklycontent', verbose_name='Haftalık İçerik'),
        ),
    ]
