# Generated by Django 6.0 on 2026-02-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0006_alter_flashcard_options_remove_flashcard_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='activity_url',
            field=models.TextField(help_text='Microsoft Learning Activities veya iframe destekli flashcard linkini buraya yapıştırın.', verbose_name='Aktivite Linki'),
        ),
    ]
