# Generated by Django 6.0 on 2026-02-05 23:00

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0007_alter_flashcard_activity_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flashcard',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='activity_url',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='title',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='answer',
            field=models.TextField(default=datetime.datetime(2026, 2, 5, 22, 59, 56, 455164, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flashcard',
            name='question',
            field=models.TextField(default=datetime.datetime(2026, 2, 5, 23, 0, 12, 854980, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='weekly_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='contents.weeklycontent'),
        ),
    ]
