# Generated by Django 6.0 on 2026-02-06 00:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0008_alter_flashcard_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='completedmaterial',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='completedmaterial',
            name='attempt_round',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='current_attempt_round',
            field=models.PositiveIntegerField(default=1, verbose_name='Aktif Deneme Turu'),
        ),
        migrations.AddField(
            model_name='studentquizattempt',
            name='attempt_round',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='timetracking',
            name='attempt_round',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='completedmaterial',
            unique_together={('student', 'material', 'attempt_round')},
        ),
    ]
