# Generated by Django 6.0 on 2026-02-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0009_alter_completedmaterial_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklycontent',
            name='guide_url',
            field=models.URLField(blank=True, help_text='Öğrenci bu linki açmadan diğer materyallere erişemez.', null=True, verbose_name='Haftalık Kazanım Kılavuzu (Link)'),
        ),
    ]
