# Generated by Django 6.0 on 2026-02-07 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0010_weeklycontent_guide_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklycontent',
            name='guide_url',
        ),
    ]
