# Generated by Django 6.0 on 2026-02-07 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0011_remove_weeklycontent_guide_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flashcard',
            options={'ordering': ['order'], 'verbose_name': 'Haftalık Kaynak', 'verbose_name_plural': 'Haftalık Kaynaklar'},
        ),
        migrations.AddField(
            model_name='timetracking',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contents.material'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='answer',
            field=models.TextField(verbose_name='OneDrive Linki'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='question',
            field=models.TextField(verbose_name='Kaynak Başlığı'),
        ),
        migrations.AlterField(
            model_name='material',
            name='content_type',
            field=models.CharField(choices=[('video', 'Video'), ('podcast', 'Podcast'), ('form', 'Bilgi Testi'), ('pdf', 'Ders Notu (PDF)'), ('assignment', 'Ödev (Microsoft Form)')], max_length=10),
        ),
    ]
