# Generated by Django 6.0 on 2026-02-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0012_alter_flashcard_options_timetracking_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklycontent',
            name='intro_description',
            field=models.TextField(blank=True, null=True, verbose_name='Tanıtım Metni/Açıklaması'),
        ),
    ]
