# Generated by Django 6.0 on 2026-02-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0013_weeklycontent_intro_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='point_value',
            field=models.PositiveIntegerField(default=1, verbose_name='Tamamlama Puanı'),
        ),
    ]
