# Generated by Django 6.0 on 2026-05-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0014_alter_material_point_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='explanation',
            field=models.TextField(blank=True, help_text='Öğrenci bu soruyu yanlış yaptığında gösterilecek hazır yapay zeka veya hoca analizi.', null=True, verbose_name='Soru Analizi / Açıklaması'),
        ),
    ]
