# Generated by Django 6.0 on 2026-10-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0015_quizquestion_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquestion',
            name='response_text',
            field=models.TextField(blank=True, null=True, verbose_name='Yapay Zeka Yanıtı'),
        ),
    ]
