# Generated by Django 6.0 on 2026-10-06 16:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0016_studentquestion_response_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='completedmaterial',
            options={'verbose_name': 'Tamamlanan Materyal', 'verbose_name_plural': 'Tamamlanan Materyaller'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Materyal', 'verbose_name_plural': 'Materyaller'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'Sınav', 'verbose_name_plural': 'Sınavlar'},
        ),
        migrations.AlterModelOptions(
            name='quizoption',
            options={'verbose_name': 'Sınav Şıkkı', 'verbose_name_plural': 'Sınav Şıkları'},
        ),
        migrations.AlterModelOptions(
            name='quizquestion',
            options={'ordering': ['order'], 'verbose_name': 'Sınav Sorusu', 'verbose_name_plural': 'Sınav Soruları'},
        ),
        migrations.AlterModelOptions(
            name='studentanswer',
            options={'verbose_name': 'Öğrenci Cevabı', 'verbose_name_plural': 'Öğrenci Cevapları'},
        ),
        migrations.AlterModelOptions(
            name='studentquestion',
            options={'verbose_name': 'Öğrenci Sorusu', 'verbose_name_plural': 'Öğrenci Soruları'},
        ),
        migrations.AlterModelOptions(
            name='studentquizattempt',
            options={'verbose_name': 'Sınav Denemesi', 'verbose_name_plural': 'Sınav Denemeleri'},
        ),
        migrations.AlterModelOptions(
            name='timetracking',
            options={'verbose_name': 'Zaman Takibi', 'verbose_name_plural': 'Zaman Takip Kayıtları'},
        ),
        migrations.AddIndex(
            model_name='completedmaterial',
            index=models.Index(fields=['student', 'attempt_round'], name='contents_co_student_bdacad_idx'),
        ),
        migrations.AddIndex(
            model_name='completedmaterial',
            index=models.Index(fields=['material', 'attempt_round'], name='contents_co_materia_328bc6_idx'),
        ),
        migrations.AddIndex(
            model_name='completedmaterial',
            index=models.Index(fields=['student', 'material', 'attempt_round'], name='contents_co_student_6c6011_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['weekly_content', 'order'], name='contents_fl_weekly__23df6b_idx'),
        ),
        migrations.AddIndex(
            model_name='introvideocompletion',
            index=models.Index(fields=['student', 'is_watched'], name='contents_in_student_e45071_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['parent_content', 'content_type'], name='contents_ma_parent__a862a0_idx'),
        ),
        migrations.AddIndex(
            model_name='quizoption',
            index=models.Index(fields=['question', 'is_correct'], name='contents_qu_questio_0415e4_idx'),
        ),
        migrations.AddIndex(
            model_name='quizquestion',
            index=models.Index(fields=['quiz', 'order'], name='contents_qu_quiz_id_f0fb3b_idx'),
        ),
        migrations.AddIndex(
            model_name='studentanswer',
            index=models.Index(fields=['attempt', 'is_correct'], name='contents_st_attempt_16d03f_idx'),
        ),
        migrations.AddIndex(
            model_name='studentanswer',
            index=models.Index(fields=['question', 'is_correct'], name='contents_st_questio_535828_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprogress',
            index=models.Index(fields=['student', 'weekly_content'], name='contents_st_student_dd94fa_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprogress',
            index=models.Index(fields=['student', 'is_completed'], name='contents_st_student_4c5123_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprogress',
            index=models.Index(fields=['student', 'current_attempt_round'], name='contents_st_student_e85868_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprogress',
            index=models.Index(fields=['weekly_content', 'is_completed'], name='contents_st_weekly__85d59d_idx'),
        ),
        migrations.AddIndex(
            model_name='studentquestion',
            index=models.Index(fields=['student', 'weekly_content'], name='contents_st_student_eb755e_idx'),
        ),
        migrations.AddIndex(
            model_name='studentquestion',
            index=models.Index(fields=['weekly_content', '-created_at'], name='contents_st_weekly__962d5d_idx'),
        ),
        migrations.AddIndex(
            model_name='studentquestion',
            index=models.Index(fields=['student', '-created_at'], name='contents_st_student_af2051_idx'),
        ),
        migrations.AddIndex(
            model_name='studentquestion',
            index=models.Index(fields=['created_at'], name='contents_st_created_ad973a_idx'),
        ),
        migrations.AddIndex(
            model_name='studentquizattempt',
            index=models.Index(fields=['student', 'quiz', 'attempt_round'], name='contents_st_student_c4bc95_idx'),
        ),
        migrations.AddIndex(
            model_name='studentquizattempt',
            index=models.Index(fields=['student', '-completed_at'], name='contents_st_student_2b6c9b_idx'),
        ),
        migrations.AddIndex(
            model_name='studentquizattempt',
            index=models.Index(fields=['quiz', 'attempt_round'], name='contents_st_quiz_id_1c112d_idx'),
        ),
        migrations.AddIndex(
            model_name='timetracking',
            index=models.Index(fields=['student', 'weekly_content', 'attempt_round'], name='contents_ti_student_348ad1_idx'),
        ),
        migrations.AddIndex(
            model_name='timetracking',
            index=models.Index(fields=['student', 'material', 'attempt_round'], name='contents_ti_student_e6e243_idx'),
        ),
        migrations.AddIndex(
            model_name='timetracking',
            index=models.Index(fields=['student', 'date'], name='contents_ti_student_d1517c_idx'),
        ),
        migrations.AddIndex(
            model_name='timetracking',
            index=models.Index(fields=['weekly_content', 'attempt_round'], name='contents_ti_weekly__9e7b6d_idx'),
        ),
        migrations.AddIndex(
            model_name='timetracking',
            index=models.Index(fields=['material', 'attempt_round'], name='contents_ti_materia_378b5b_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklycontent',
            index=models.Index(fields=['week_number'], name='contents_we_week_nu_17ada4_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklycontent',
            index=models.Index(fields=['release_date'], name='contents_we_release_d3d0b2_idx'),
        ),
    ]
