# Generated by Django 6.0 on 2026-10-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0017_alter_completedmaterial_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquizattempt',
            name='predicted_score',
            field=models.IntegerField(default=0, verbose_name='Tahmin Edilen Skor'),
        ),
        migrations.AddField(
            model_name='studentquizattempt',
            name='score_difference',
            field=models.IntegerField(default=0, verbose_name='Skor Farkı (Gerçek - Tahmin)'),
        ),
    ]
