# Generated by Django 6.0 on 2026-10-07 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0018_studentquizattempt_predicted_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyContentDepartmentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('ilahiyat', 'İlahiyat'), ('isg', 'İş Sağlığı Ve Güvenliği'), ('beslenmevediyetetik', 'Beslenme Ve Diyetetik'), ('hemsirelik', 'Hemşirelik'), ('saglikyonetimi', 'Sağlık Yönetimi'), ('webtasarimvekodlama', 'Web Tasarım Ve Kodlama')], max_length=50, verbose_name='Bölüm')),
                ('release_date', models.DateTimeField(blank=True, help_text='Bu tarih gelmeden ilgili bölümdeki öğrenci içeriğe erişemez.', null=True, verbose_name='Erişime Açılma Tarihi')),
                ('deactivation_date', models.DateTimeField(blank=True, help_text='Bu tarih geçtikten sonra ilgili bölümdeki öğrenci içeriğe erişemez.', null=True, verbose_name='Pasif Etme / Kapanma Tarihi')),
            ],
            options={
                'verbose_name': 'Bölüm Bazlı Hafta Tarih Ayarı',
                'verbose_name_plural': 'Bölüm Bazlı Hafta Tarih Ayarları',
            },
        ),
        migrations.AddField(
            model_name='weeklycontent',
            name='deactivation_date',
            field=models.DateTimeField(blank=True, help_text='Bu tarih geçtikten sonra öğrenci içeriğe erişemez.', null=True, verbose_name='Pasif Etme / Kapanma Tarihi'),
        ),
        migrations.AddIndex(
            model_name='weeklycontent',
            index=models.Index(fields=['deactivation_date'], name='contents_we_deactiv_d29570_idx'),
        ),
        migrations.AddField(
            model_name='weeklycontentdepartmentschedule',
            name='weekly_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_schedules', to='contents.weeklycontent', verbose_name='Haftalık İçerik'),
        ),
        migrations.AddIndex(
            model_name='weeklycontentdepartmentschedule',
            index=models.Index(fields=['weekly_content', 'department'], name='contents_we_weekly__886c3c_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklycontentdepartmentschedule',
            index=models.Index(fields=['department', 'release_date', 'deactivation_date'], name='contents_we_departm_69c370_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='weeklycontentdepartmentschedule',
            unique_together={('weekly_content', 'department')},
        ),
    ]
