# Generated by Django 6.0 on 2026-10-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0019_weeklycontentdepartmentschedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, default=120, null=True, verbose_name='Tamamlama Süresi (Saniye)'),
        ),
    ]
