# Generated by Django 6.0 on 2026-10-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0020_material_duration_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklycontentdepartmentschedule',
            name='department',
            field=models.CharField(choices=[('siyasetbilimivekamuyonetimi', 'Siyaset Bilimi Ve Kamu Yönetimi'), ('turkdiliveedebiyati', 'Türk Dili Ve Edebiyatı'), ('matematik', 'Matematik')], max_length=50, verbose_name='Bölüm'),
        ),
    ]
